In [13]:
import numpy as np

In [15]:

array = np.array([0,1,2,3,4,5])
array, type(array)
notas = [16,17,14,17,19,15]
ar_notas = np.array(notas, dtype=float)
ar_notas, type(ar_notas[0])

(array([16., 17., 14., 17., 19., 15.]), numpy.float64)

In [16]:


ar_notas_todas = np.array(([0,1,2,3,4,5], notas))
print(ar_notas_todas)

[[ 0  1  2  3  4  5]
 [16 17 14 17 19 15]]


ndim, para conocer el numero de dimensiones del array


In [5]:
print(ar_notas_todas.ndim)
print(ar_notas.ndim)

2
1


shape, para conocer el tamaño de cada dimension

In [7]:
print(ar_notas_todas.shape)
print(ar_notas.shape)

(2, 6)
(6,)


Arrays especiales:

    - zeros: Produce un ndarray con todos sus elementos igual a cero.

    - ones: produce un ndarray con todos sus elementos igual a uno.

    - indentity: produce una matriz cuadrada identidad.
    
    - arange: produce un nuevo ndarray cuyos elementos esta en el rango especificado.
    

In [9]:
arr = np.zeros((2,3), dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr2 = np.ones((3,4), dtype=float)
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
arr3 = np.identity((4), dtype=float)
print(arr3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
arr4 = np.arange(1,9)
print(arr4)

[1 2 3 4 5 6 7 8]
