<font color=Green>
    
# **2.4 Álgebra lineal**

</font>

## <font color=#003d5c>_Producto de arrays_ </font>

In [4]:
import numpy as np

a = np.array([1, 2, 3], float) 
b = np.array([0, 1, 1], float) 

np.dot(b, a) #multiplicar

5.0

In [ ]:
a.dot(b) #array por el que lo quiero multiplicar

5.0

## <font color=#003d5c>_Producto de matrices_ </font>

In [5]:
a = np.array([[5, 2], [4, 8]], float) 
b = np.array([[2, 4], [5, 3]], float) 

print(a, "\n ---------------")
print(b, "\n ---------------")

[[5. 2.]
 [4. 8.]] 
 ---------------
[[2. 4.]
 [5. 3.]] 
 ---------------


In [ ]:
np.dot(a, b)
#primero multiplica la fila del primer array por la columna del segundo, asi da los resultados 20 y 26
#(5*2 =10) + (2*5 = 10) =20, 
# (5*4 =20) + (2*3 =6) =26 
#luego continua con la segunda fila  el primer array que hace lo mismo
#(4*2 =8) + (8*5 = 40) =48, 
# (4*4 =16) + (8*3 =24) =40 

array([[20., 26.],
       [48., 40.]])

In [7]:
a @ b

array([[20., 26.],
       [48., 40.]])

In [16]:
a = np.array([[0, 1, 4], [5, 2, 3], [1, 4, 8]], float) 

b = np.array([2, 3, 5], float) 

print(a,"\n ---------------")
print(b, "\n ---------------")

[[0. 1. 4.]
 [5. 2. 3.]
 [1. 4. 8.]] 
 ---------------
[2. 3. 5.] 
 ---------------


In [14]:
np.dot(a,b)
#(0*2=0) + (1*3=3) + (4*5=20) = 23
#(5*2=10) + (2*3=6) + (3*5=15) = 31
#(1*2= 2) + (4*3=12) + (8*5=40) = 54


array([23., 31., 54.])

In [12]:
a @ b

array([23., 31., 54.])

In [13]:
print(np.matmul(a,b))

[23. 31. 54.]


## <font color=#003d5c>_Determinante de una matriz_ </font>

In [18]:
a = np.array([[8, 5], [3, 4]])

print(a, "\n ---------------")

np.linalg.det(a)
#(8*4) - (3*5) = 32 - 15 = 17

[[8 5]
 [3 4]] 
 ---------------


17.0

## <font color=#003d5c>_Auto-valores y auto-vectores_ </font>

In [20]:
vals, vecs = np.linalg.eig(a)
#asigna el primer elemento a la primera variable (autovalores)y el segundo a la segunda (autovectores)

print(vals, "\n ---------------")
print(vecs, "\n ---------------")

[10.35889894  1.64110106] 
 ---------------
[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]] 
 ---------------
