<font color=Green>
    
# **2.7 Agregar y quitar valores a un array**

</font>

In [ ]:
import numpy as np

arr = np.arange(0,20,2) #del 0 al 20, saltando de 2 en 2
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
arr_flot = np.random.rand(4,3) #random, 4 filas y 3 columnas de elementos entre 0 y 1
arr_flot

array([[0.95960282, 0.01403578, 0.72305054],
       [0.94198556, 0.05098518, 0.9339188 ],
       [0.17433379, 0.99880402, 0.05024614],
       [0.87404859, 0.23393181, 0.97775067]])

In [29]:
arr_ent = np.random.randint(100, size=(2,3)) #2 filas, 3 columnas, numeros entre 0 y 100
arr_ent

array([[56, 18, 85],
       [79, 74, 27]])

In [ ]:
arr_6 = np.full((3,3),6) 
#3 filas, 3 columnas, donde todos los elementos son en este caso 6
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [ ]:
np.append(arr, [12,13,14,51]) #añadir al array que tenemos

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [ ]:
np.insert(arr,2, [42,34]) #insertar en el array en la posicion 2, esos datos

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.insert(arr_6,2, [1,2,4])#insertar en el array en la posicion 2, esos datos

array([6, 6, 1, 2, 4, 6, 6, 6, 6, 6, 6, 6])

In [36]:
np.delete(arr_ent,0,axis=1) #eliminar el dato en la posicion 0 eje 1

array([[18, 85],
       [74, 27]])