<font color=Green>
    
# **2.8 Transformaciones**

</font>


## <font color=#003d5c>_As Type_ </font>

### Este método nos permite modificar el tipo de dato de los valores de un `array`

In [16]:
import numpy as np

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[67, 21, 51,  7],
       [58, 23, 81, 98],
       [85, 21, 95, 20]])

In [ ]:
arr_ent.astype(float) #cambiar tipo de dato

array([[11., 12., 13., 19.],
       [61., 18., 42., 94.],
       [63., 27., 54., 44.]])

## <font color=#003d5c>_Sort_ </font>

### Este método nos permite ordenar los valores de un `array`

In [17]:
arr_ent

array([[67, 21, 51,  7],
       [58, 23, 81, 98],
       [85, 21, 95, 20]])

In [ ]:
arr_ent.sort() #ordenar cada fila
arr_ent

array([[ 7, 21, 51, 67],
       [23, 58, 81, 98],
       [20, 21, 85, 95]])

In [ ]:
arr_ent.sort(axis=0) #ordenar todo
arr_ent

array([[ 7, 21, 51, 67],
       [20, 21, 81, 95],
       [23, 58, 85, 98]])

## <font color=#003d5c>_Reshape_ </font>

### Este método nos permite modificar las dimensiones de un `array`.

In [20]:
arr_ent

array([[ 7, 21, 51, 67],
       [20, 21, 81, 95],
       [23, 58, 85, 98]])

In [ ]:
arr_ent = arr_ent.reshape(4,3) #reordenar tamaño de filas y culumnas (debe tener la misma cantidad de elementos)
arr_ent

array([[ 7, 21, 51],
       [67, 20, 21],
       [81, 95, 23],
       [58, 85, 98]])

## <font color=#003d5c>_Flatten_ </font>

### Este método crea un array unidimensional desde el original.

In [23]:
plano_arr = arr_ent.flatten() #el array multidimensional en uno solo normal

print(arr_ent)
print(plano_arr)

[[ 7 21 51]
 [67 20 21]
 [81 95 23]
 [58 85 98]]
[ 7 21 51 67 20 21 81 95 23 58 85 98]


## <font color=#003d5c>_To List_ </font>

### Este método crea una lista a partir de un array

In [ ]:
lista_arr = plano_arr.tolist() #cambia tipo a lista
lista_arr
type(lista_arr)

list

## <font color=#003d5c>_Separar y juntar arrays_ </font>

In [ ]:
arrays= np.split(arr_ent,4) ~#separa en arrays, cantidad de arrays que queremos obtener
arrays

[array([[ 7, 21, 51]]),
 array([[67, 20, 21]]),
 array([[81, 95, 23]]),
 array([[58, 85, 98]])]

In [35]:
np.concatenate((arrays[1],arrays[0]),axis=1) #0 para vertical, 1 para horizontal
#np.concatenate((arrays[1],arrays[0]),axis=0)
#concadena los arrays de "arrays" en posicion 0 y uno con una sola fila

array([[67, 20, 21,  7, 21, 51]])

## <font color=#003d5c>_La matriz transpuesta_ </font>

In [36]:
arr_ent

array([[ 7, 21, 51],
       [67, 20, 21],
       [81, 95, 23],
       [58, 85, 98]])

In [ ]:
t_arr = arr_ent.T #cambia las posiones de filas con columnas
t_arr

array([[ 7, 67, 81, 58],
       [21, 20, 95, 85],
       [51, 21, 23, 98]])