## <font color=green>2.9 Indexación y slicing</font>

### El slicing (filtrado) sigue la siguiente forma _`[i:j:k]`_ 
### Donde _i_ es el índice inicial; _j_ es el índice de parada; y _k_ es el incremento (step) no nulo.

In [7]:
import numpy as np

a = np.array(range(64)).reshape((8,8)) 
#crea 8 arrays con los numeros repartidos hasta el 64
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
a[1,1] #indice, fila numero1, columna 1 (siempre hay una 0 como primera)

9

In [ ]:
a[0:7:2,0:4] #desde la 0 a la 7 de dos en dos, los 4 primeros numeros

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [32, 33, 34, 35],
       [48, 49, 50, 51]])

In [ ]:
a[1,3:5] #en la fila 1 cogeme el elemento 3 hasta el 5

array([11, 12])

In [ ]:
a[[1,3,5],[3,6,7]]#fila1,elemento3 + fila 3, elemeto 6 + fila 5 elemento 7

array([11, 30, 47])

In [ ]:
a[[1,3,5],::3] #en las filas 1,3 y 5, cogeme los elementos saltando de 3 en 3

array([[ 8, 11, 14],
       [24, 27, 30],
       [40, 43, 46]])

## <font color=#003d5c> _Indexación booleana_ </font>

In [9]:
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
data < 4 #que elementos son menores de 4

array([ True,  True,  True,  True, False, False, False, False])

In [ ]:
data[data<4] #dime los valores culla posicion no sea mas de 4

array([0, 1, 2, 3])

In [ ]:
data[np.array([True,  True,  True,  True, False, False, False, False])]
#dime los elementos con true

array([0, 1, 2, 3])

In [14]:
amigos = np.array(['giulia', 'victor', 'johel', 'andreina', 'valentina', 'albert', 'roque'])

In [ ]:
'giulia' in amigos #esta "cadena", en amigos

True

In [ ]:
amigos[amigos!='giulia'] #elementos dentro sea distinto a

array(['victor', 'johel', 'andreina', 'valentina', 'albert', 'roque'],
      dtype='<U9')

In [ ]:
amigos[amigos=='giulia'] #elemetos iguales a

array(['giulia'], dtype='<U9')